# Pandas

What is pandas? 

1. Browse the pandas docs here: [https://pandas.pydata.org/docs/getting_started/index.html#getting-started](https://pandas.pydata.org/docs/getting_started/index.html#getting-started)
2. Most people would be familar with Excel, so the easiest way to understand pandas is by comparing it to excel: [https://pandas.pydata.org/docs/getting_started/comparison/comparison_with_spreadsheets.html#compare-with-spreadsheets](https://pandas.pydata.org/docs/getting_started/comparison/comparison_with_spreadsheets.html#compare-with-spreadsheets)

In [1]:
import pandas as pd

We are now going to read in a CSV into a DataFrame. A DataFrame is similar to a table or worksheet in Excel. 

Reading a CSV can be done by executing `pd.read_csv("path_to_your_file.csv")`

Run the cell below and notice the following: 
1. The data is formatted as a table (similar to excel)
2. We have an index column (the first column without a name and starts from 0) which is similar to the row number in excel
3. We have column headers (similar to excel)

In [2]:
# read a CSV into a DataFrame
pd.read_csv("https://raw.githubusercontent.com/AustralianSDAF/python-data-visualisation/main/perth_house_prices.csv")

,ADDRESS,SUBURB,PRICE,BEDROOMS,BATHROOMS,GARAGE,LAND_AREA,FLOOR_AREA,BUILD_YEAR,CBD_DIST,NEAREST_STN,NEAREST_STN_DIST,DATE_SOLD,POSTCODE,LATITUDE,LONGITUDE,NEAREST_SCH,NEAREST_SCH_DIST,NEAREST_SCH_RANK
0,1 Acorn Place,South Lake,565000,4,2,2.0,600,160,2003.0,18300,Cockburn Central Station,1800,09-2018\r,6164,-32.115900,115.842450,LAKELAND SENIOR HIGH SCHOOL,0.828339,NaN
1,1 Addis Way,Wandi,365000,3,2,2.0,351,139,2013.0,26900,Kwinana Station,4900,02-2019\r,6167,-32.193470,115.859554,ATWELL COLLEGE,5.524324,129.0
2,1 Ainsley Court,Camillo,287000,3,1,1.0,719,86,1979.0,22600,Challis Station,1900,06-2015\r,6111,-32.120578,115.993579,KELMSCOTT SENIOR HIGH SCHOOL,1.649178,113.0
3,1 Albert Street,Bellevue,255000,2,1,2.0,651,59,1953.0,17900,Midland Station,3600,07-2018\r,6056,-31.900547,116.038009,SWAN VIEW SENIOR HIGH SCHOOL,1.571401,NaN
4,1 Aman Place,Lockridge,325000,4,1,2.0,466,131,1998.0,11200,Bassendean Station,2000,11-2016\r,6054,-31.885790,115.947780,KIARA COLLEGE,1.514922,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33651,9C Gold Street,South Fremantle,1040000,4,3,2.0,292,245,2013.0,16100,Fremantle Station,1500,03-2016\r,6162,-32.064580,115.751820,CHRISTIAN BROTHERS' COLLEGE,1.430350,49.0
33652,9C Pycombe Way,Westminster,410000,3,2,2.0,228,114,NaN,9600,Stirling Station,4600,02-2017\r,6061,-31.867055,115.841403,JOHN SEPTIMUS ROE ANGLICAN COMMUNITY SCHOOL,1.679644,35.0
33653,9D Pycombe Way,Westminster,427000,3,2,2.0,261,112,NaN,9600,Stirling Station,4600,02-2017\r,6061,-31.866890,115.841418,JOHN SEPTIMUS ROE ANGLICAN COMMUNITY SCHOOL,1.669159,35.0
33654,9D Shalford Way,Girrawheen,295000,3,1,2.0,457,85,1974.0,12600,Warwick Station,4400,10-2016\r,6064,-31.839680,115.842410,GIRRAWHEEN SENIOR HIGH SCHOOL,0.358494,NaN
33655,9E Margaret Street,Midland,295000,3,1,2.0,296,95,NaN,16700,Midland Station,1700,05-2016\r,6056,-31.882163,116.014755,LA SALLE COLLEGE,1.055564,53.0

In [3]:
# we often like to read store the DataFrame as a variable so that we can access it later
df = pd.read_csv("https://raw.githubusercontent.com/AustralianSDAF/python-data-visualisation/main/perth_house_prices.csv")

In [4]:
# show  the first 5 rows
df.head(5)

,ADDRESS,SUBURB,PRICE,BEDROOMS,BATHROOMS,GARAGE,LAND_AREA,FLOOR_AREA,BUILD_YEAR,CBD_DIST,NEAREST_STN,NEAREST_STN_DIST,DATE_SOLD,POSTCODE,LATITUDE,LONGITUDE,NEAREST_SCH,NEAREST_SCH_DIST,NEAREST_SCH_RANK
0,1 Acorn Place,South Lake,565000,4,2,2.0,600,160,2003.0,18300,Cockburn Central Station,1800,09-2018\r,6164,-32.115900,115.842450,LAKELAND SENIOR HIGH SCHOOL,0.828339,NaN
1,1 Addis Way,Wandi,365000,3,2,2.0,351,139,2013.0,26900,Kwinana Station,4900,02-2019\r,6167,-32.193470,115.859554,ATWELL COLLEGE,5.524324,129.0
2,1 Ainsley Court,Camillo,287000,3,1,1.0,719,86,1979.0,22600,Challis Station,1900,06-2015\r,6111,-32.120578,115.993579,KELMSCOTT SENIOR HIGH SCHOOL,1.649178,113.0
3,1 Albert Street,Bellevue,255000,2,1,2.0,651,59,1953.0,17900,Midland Station,3600,07-2018\r,6056,-31.900547,116.038009,SWAN VIEW SENIOR HIGH SCHOOL,1.571401,NaN
4,1 Aman Place,Lockridge,325000,4,1,2.0,466,131,1998.0,11200,Bassendean Station,2000,11-2016\r,6054,-31.885790,115.947780,KIARA COLLEGE,1.514922,NaN

In [5]:
# show the last 5 rows
df.tail(5)

,ADDRESS,SUBURB,PRICE,BEDROOMS,BATHROOMS,GARAGE,LAND_AREA,FLOOR_AREA,BUILD_YEAR,CBD_DIST,NEAREST_STN,NEAREST_STN_DIST,DATE_SOLD,POSTCODE,LATITUDE,LONGITUDE,NEAREST_SCH,NEAREST_SCH_DIST,NEAREST_SCH_RANK
33651,9C Gold Street,South Fremantle,1040000,4,3,2.0,292,245,2013.0,16100,Fremantle Station,1500,03-2016\r,6162,-32.064580,115.751820,CHRISTIAN BROTHERS' COLLEGE,1.430350,49.0
33652,9C Pycombe Way,Westminster,410000,3,2,2.0,228,114,NaN,9600,Stirling Station,4600,02-2017\r,6061,-31.867055,115.841403,JOHN SEPTIMUS ROE ANGLICAN COMMUNITY SCHOOL,1.679644,35.0
33653,9D Pycombe Way,Westminster,427000,3,2,2.0,261,112,NaN,9600,Stirling Station,4600,02-2017\r,6061,-31.866890,115.841418,JOHN SEPTIMUS ROE ANGLICAN COMMUNITY SCHOOL,1.669159,35.0
33654,9D Shalford Way,Girrawheen,295000,3,1,2.0,457,85,1974.0,12600,Warwick Station,4400,10-2016\r,6064,-31.839680,115.842410,GIRRAWHEEN SENIOR HIGH SCHOOL,0.358494,NaN
33655,9E Margaret Street,Midland,295000,3,1,2.0,296,95,NaN,16700,Midland Station,1700,05-2016\r,6056,-31.882163,116.014755,LA SALLE COLLEGE,1.055564,53.0

In [11]:
# selecting only "BEDROOMS", "SUBURB" and "PRICES" columns 
df[["SUBURB", "BEDROOMS", "PRICE"]].head(5)

       SUBURB  BEDROOMS   PRICE
0  South Lake         4  565000
1       Wandi         3  365000
2     Camillo         3  287000
3    Bellevue         2  255000
4   Lockridge         4  325000

In [12]:
# creating a new column: "free_space" = "LAND_AREA" - "FLOOR_AREA"
df["free_space"] = df["LAND_AREA"] - df["FLOOR_AREA"]
df[["free_space", "LAND_AREA", "FLOOR_AREA"]].head(5)

   free_space  LAND_AREA  FLOOR_AREA
0         440        600         160
1         212        351         139
2         633        719          86
3         592        651          59
4         335        466         131

In [15]:
# creating a new column called "AGE" = 2021 - "BUILD_YEAR"
df["age"] = 2021 - df["BUILD_YEAR"]
df[["age", "BUILD_YEAR"]].head(5)

    age  BUILD_YEAR
0  18.0      2003.0
1   8.0      2013.0
2  42.0      1979.0
3  68.0      1953.0
4  23.0      1998.0

# Filtering

The below statement is simply passing a Series of True/False objects to the DataFrame, returning all rows with True.

In [18]:
# similarly, we can filter our DataFrame by doing: 

df[df["age"] < 5] # filters where age < 5

,ADDRESS,SUBURB,PRICE,BEDROOMS,BATHROOMS,GARAGE,LAND_AREA,FLOOR_AREA,BUILD_YEAR,CBD_DIST,...,NEAREST_STN_DIST,DATE_SOLD,POSTCODE,LATITUDE,LONGITUDE,NEAREST_SCH,NEAREST_SCH_DIST,NEAREST_SCH_RANK,free_space,age
145,1 Eastfield Court,Ferndale,250000,3,1,1.0,955,396,2017.0,11400,...,2700,07-2016\r,6148,-32.030990,115.935361,FOUNTAIN COLLEGE,1.571154,NaN,559,4.0
9209,183A Salisbury Street,Bedford,690000,4,2,2.0,532,247,2017.0,5200,...,2800,04-2018\r,6052,-31.909876,115.882484,CHISHOLM CATHOLIC COLLEGE,1.716868,29.0,285,4.0
10148,2 Barnsley Street,Queens Park,480000,4,2,2.0,664,94,2017.0,9800,...,1400,08-2017\r,6107,-32.001055,115.945425,ST NORBERT COLLEGE,0.604300,42.0,570,4.0
26971,6 La Fayette Boulevard,Bibra Lake,565000,4,2,NaN,806,312,2017.0,16100,...,4400,07-2016\r,6163,-32.091380,115.814210,PERTH WALDORF SCHOOL,0.337237,NaN,494,4.0
30349,77a York Street,Beaconsfield,835000,4,2,2.0,587,159,2017.0,15400,...,3400,11-2018\r,6162,-32.069893,115.773769,FREMANTLE COLLEGE,0.588550,128.0,428,4.0
32409,9 Covenham Crescent,Aveley,430000,4,2,2.0,375,160,2017.0,22400,...,11700,10-2020\r,6069,-31.786825,115.994063,SWAN VALLEY ANGLICAN COMMUNITY SCHOOL,1.167177,53.0,215,4.0

In [19]:
# we can filter with multiple conditions by doing 
df[(df["age"] < 10) & (df["BEDROOMS"]==4)] # filters where age <> 10 and BEDROOMS == 4

,ADDRESS,SUBURB,PRICE,BEDROOMS,BATHROOMS,GARAGE,LAND_AREA,FLOOR_AREA,BUILD_YEAR,CBD_DIST,...,NEAREST_STN_DIST,DATE_SOLD,POSTCODE,LATITUDE,LONGITUDE,NEAREST_SCH,NEAREST_SCH_DIST,NEAREST_SCH_RANK,free_space,age
7,1 Arnside Bend,Waikiki,370000,4,2,2.0,468,158,2013.0,41700,...,1100,03-2019\r,6169,-32.317662,115.761968,SOUTH COAST BAPTIST COLLEGE,0.491573,NaN,310,8.0
28,1 Belfry Way,Wattle Grove,492000,4,2,2.0,459,250,2012.0,14100,...,5100,11-2017\r,6107,-32.004154,115.994959,HERITAGE COLLEGE PERTH,3.374077,NaN,209,9.0
52,1 Bradstocks Grove,Southern River,780000,4,2,2.0,447,305,2015.0,18600,...,5800,09-2018\r,6110,-32.099349,115.952568,PROVIDENCE CHRISTIAN COLLEGE,1.496350,38.0,142,6.0
71,1 Cameron Street,Karrinyup,1350000,4,1,5.0,802,266,2012.0,12000,...,3500,03-2018\r,6018,-31.870983,115.775959,ST MARY'S ANGLICAN GIRLS' SCHOOL,1.133916,7.0,536,9.0
86,1 Charleston Road,Eglinton,495000,4,2,2.0,432,155,2015.0,43700,...,5400,02-2016\r,6034,-31.594758,115.668969,YANCHEP SECONDARY COLLEGE,5.284580,NaN,277,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33600,9A Elizabeth Street,White Gum Valley,830000,4,2,2.0,320,220,2015.0,14800,...,2700,01-2018\r,6162,-32.062786,115.771299,FREMANTLE COLLEGE,0.650144,128.0,100,6.0
33607,9A Henning Crescent,Manning,1220000,4,2,2.0,477,352,2016.0,6900,...,1200,02-2019\r,6152,-32.013968,115.867651,COMO SECONDARY COLLEGE,1.192793,87.0,125,5.0
33638,9B Crawshaw Crescent,Manning,1140000,4,2,2.0,476,206,2015.0,6100,...,925,04-2016\r,6152,-32.007101,115.865513,COMO SECONDARY COLLEGE,0.655247,87.0,270,6.0
33649,9B Viveash Road,Middle Swan,467000,4,2,2.0,400,132,2014.0,17100,...,2500,04-2015\r,6056,-31.872192,116.013543,LA SALLE COLLEGE,1.116806,53.0,268,7.0
33651,9C Gold Street,South Fremantle,1040000,4,3,2.0,292,245,2013.0,16100,...,1500,03-2016\r,6162,-32.064580,115.751820,CHRISTIAN BROTHERS' COLLEGE,1.430350,49.0,47,8.0

# If/then logic
Let’s say we want to make a comment column with values of low and high, based on whether the PRICE is less or more than $1000000.

In [21]:
import numpy as np

In [26]:
# perform the if/then statement by using np.where()
df["comment"] = np.where(df["PRICE"] < 1000000, "low", "high")
df.head(5)

,ADDRESS,SUBURB,PRICE,BEDROOMS,BATHROOMS,GARAGE,LAND_AREA,FLOOR_AREA,BUILD_YEAR,CBD_DIST,...,POSTCODE,LATITUDE,LONGITUDE,NEAREST_SCH,NEAREST_SCH_DIST,NEAREST_SCH_RANK,free_space,age,bucket,comment
0,1 Acorn Place,South Lake,565000,4,2,2.0,600,160,2003.0,18300,...,6164,-32.115900,115.842450,LAKELAND SENIOR HIGH SCHOOL,0.828339,NaN,440,18.0,low,low
1,1 Addis Way,Wandi,365000,3,2,2.0,351,139,2013.0,26900,...,6167,-32.193470,115.859554,ATWELL COLLEGE,5.524324,129.0,212,8.0,low,low
2,1 Ainsley Court,Camillo,287000,3,1,1.0,719,86,1979.0,22600,...,6111,-32.120578,115.993579,KELMSCOTT SENIOR HIGH SCHOOL,1.649178,113.0,633,42.0,low,low
3,1 Albert Street,Bellevue,255000,2,1,2.0,651,59,1953.0,17900,...,6056,-31.900547,116.038009,SWAN VIEW SENIOR HIGH SCHOOL,1.571401,NaN,592,68.0,low,low
4,1 Aman Place,Lockridge,325000,4,1,2.0,466,131,1998.0,11200,...,6054,-31.885790,115.947780,KIARA COLLEGE,1.514922,NaN,335,23.0,low,low

In [27]:
# we can drop a column by doing
df.drop("NEAREST_SCH_RANK", axis=1) # axis=1 tells pandas to drop "NEAREST_SCH_RANK" from the columns

,ADDRESS,SUBURB,PRICE,BEDROOMS,BATHROOMS,GARAGE,LAND_AREA,FLOOR_AREA,BUILD_YEAR,CBD_DIST,...,DATE_SOLD,POSTCODE,LATITUDE,LONGITUDE,NEAREST_SCH,NEAREST_SCH_DIST,free_space,age,bucket,comment
0,1 Acorn Place,South Lake,565000,4,2,2.0,600,160,2003.0,18300,...,09-2018\r,6164,-32.115900,115.842450,LAKELAND SENIOR HIGH SCHOOL,0.828339,440,18.0,low,low
1,1 Addis Way,Wandi,365000,3,2,2.0,351,139,2013.0,26900,...,02-2019\r,6167,-32.193470,115.859554,ATWELL COLLEGE,5.524324,212,8.0,low,low
2,1 Ainsley Court,Camillo,287000,3,1,1.0,719,86,1979.0,22600,...,06-2015\r,6111,-32.120578,115.993579,KELMSCOTT SENIOR HIGH SCHOOL,1.649178,633,42.0,low,low
3,1 Albert Street,Bellevue,255000,2,1,2.0,651,59,1953.0,17900,...,07-2018\r,6056,-31.900547,116.038009,SWAN VIEW SENIOR HIGH SCHOOL,1.571401,592,68.0,low,low
4,1 Aman Place,Lockridge,325000,4,1,2.0,466,131,1998.0,11200,...,11-2016\r,6054,-31.885790,115.947780,KIARA COLLEGE,1.514922,335,23.0,low,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33651,9C Gold Street,South Fremantle,1040000,4,3,2.0,292,245,2013.0,16100,...,03-2016\r,6162,-32.064580,115.751820,CHRISTIAN BROTHERS' COLLEGE,1.430350,47,8.0,high,high
33652,9C Pycombe Way,Westminster,410000,3,2,2.0,228,114,NaN,9600,...,02-2017\r,6061,-31.867055,115.841403,JOHN SEPTIMUS ROE ANGLICAN COMMUNITY SCHOOL,1.679644,114,NaN,low,low
33653,9D Pycombe Way,Westminster,427000,3,2,2.0,261,112,NaN,9600,...,02-2017\r,6061,-31.866890,115.841418,JOHN SEPTIMUS ROE ANGLICAN COMMUNITY SCHOOL,1.669159,149,NaN,low,low
33654,9D Shalford Way,Girrawheen,295000,3,1,2.0,457,85,1974.0,12600,...,10-2016\r,6064,-31.839680,115.842410,GIRRAWHEEN SENIOR HIGH SCHOOL,0.358494,372,47.0,low,low
33655,9E Margaret Street,Midland,295000,3,1,2.0,296,95,NaN,16700,...,05-2016\r,6056,-31.882163,116.014755,LA SALLE COLLEGE,1.055564,201,NaN,low,low

In [28]:
# we can rename a column by passing in a key-value pair that contains: {'from': 'to'}
df = df.rename(columns={"NEAREST_SCH_DIST": "Dist_to_school"})
df.head(5)

,ADDRESS,SUBURB,PRICE,BEDROOMS,BATHROOMS,GARAGE,LAND_AREA,FLOOR_AREA,BUILD_YEAR,CBD_DIST,...,POSTCODE,LATITUDE,LONGITUDE,NEAREST_SCH,Dist_to_school,NEAREST_SCH_RANK,free_space,age,bucket,comment
0,1 Acorn Place,South Lake,565000,4,2,2.0,600,160,2003.0,18300,...,6164,-32.115900,115.842450,LAKELAND SENIOR HIGH SCHOOL,0.828339,NaN,440,18.0,low,low
1,1 Addis Way,Wandi,365000,3,2,2.0,351,139,2013.0,26900,...,6167,-32.193470,115.859554,ATWELL COLLEGE,5.524324,129.0,212,8.0,low,low
2,1 Ainsley Court,Camillo,287000,3,1,1.0,719,86,1979.0,22600,...,6111,-32.120578,115.993579,KELMSCOTT SENIOR HIGH SCHOOL,1.649178,113.0,633,42.0,low,low
3,1 Albert Street,Bellevue,255000,2,1,2.0,651,59,1953.0,17900,...,6056,-31.900547,116.038009,SWAN VIEW SENIOR HIGH SCHOOL,1.571401,NaN,592,68.0,low,low
4,1 Aman Place,Lockridge,325000,4,1,2.0,466,131,1998.0,11200,...,6054,-31.885790,115.947780,KIARA COLLEGE,1.514922,NaN,335,23.0,low,low

In [29]:
# finally, we can sort a DataFrame by doing
df.sort_values(["PRICE"]).head(10) # sort by lowest to highest bill by default

,ADDRESS,SUBURB,PRICE,BEDROOMS,BATHROOMS,GARAGE,LAND_AREA,FLOOR_AREA,BUILD_YEAR,CBD_DIST,...,POSTCODE,LATITUDE,LONGITUDE,NEAREST_SCH,Dist_to_school,NEAREST_SCH_RANK,free_space,age,bucket,comment
12509,22 Nantellis Road,Martin,51000,4,2,2.0,960,227,NaN,18500,...,6110,-32.064020,116.003760,LUMEN CHRISTI COLLEGE,0.862837,122.0,733,NaN,low,low
18489,33 Conductor Retreat,Mariginiup,52000,3,2,2.0,20058,188,1990.0,28400,...,6078,-31.696900,115.870440,JOSEPH BANKS SECONDARY COLLEGE,6.991689,92.0,19870,31.0,low,low
23030,45A Langley Crescent,Innaloo,53000,3,1,2.0,245,150,2001.0,9400,...,6018,-31.888310,115.793560,INTERNATIONAL SCHOOL OF WESTERN AUSTRALIA,1.884333,NaN,95,20.0,low,low
21098,4 Marra Mews,Jane Brook,54500,4,2,2.0,704,174,1999.0,20800,...,6056,-31.866500,116.054340,SWAN VIEW SENIOR HIGH SCHOOL,2.517697,NaN,530,22.0,low,low
19042,342 Jarrah Road,Hopeland,54500,4,2,3.0,90527,274,2011.0,47800,...,6125,-32.381420,115.873760,BALDIVIS SECONDARY COLLEGE,6.771582,134.0,90253,10.0,low,low
15824,29 Dalry Road,Darlington,55000,3,1,NaN,2966,146,1915.0,21000,...,6070,-31.913740,116.076990,TREETOPS MONTESSORI SCHOOL,0.745814,NaN,2820,106.0,low,low
17220,3/135 Alice Street,Doubleview,55000,3,2,2.0,217,102,1997.0,10300,...,6018,-31.887059,115.780933,INTERNATIONAL SCHOOL OF WESTERN AUSTRALIA,1.310480,NaN,115,24.0,low,low
33048,9 Woodland Place,Casuarina,55000,4,2,2.0,8883,198,1995.0,30600,...,6167,-32.226820,115.873090,THE KING'S COLLEGE,4.433095,NaN,8685,26.0,low,low
20921,4 Hilltop Close,Mahogany Creek,55000,4,2,2.0,1801,207,1996.0,27400,...,6072,-31.900420,116.142430,MUNDARING CHRISTIAN COLLEGE,3.578374,NaN,1594,25.0,low,low
10383,2 Hazelmere Crescent,Hazelmere,56000,3,1,2.0,1367,99,1960.0,13900,...,6055,-31.901390,115.992920,GUILDFORD GRAMMAR SCHOOL,1.324249,52.0,1268,61.0,low,low

In [30]:
df.sort_values(["PRICE"], ascending=False).head(10) # sort by highest to lowest

,ADDRESS,SUBURB,PRICE,BEDROOMS,BATHROOMS,GARAGE,LAND_AREA,FLOOR_AREA,BUILD_YEAR,CBD_DIST,...,POSTCODE,LATITUDE,LONGITUDE,NEAREST_SCH,Dist_to_school,NEAREST_SCH_RANK,free_space,age,bucket,comment
19255,35 Oakdale Street,Floreat,2440000,6,4,2.0,809,442,2009.0,6800,...,6014,-31.940600,115.787720,NEWMAN COLLEGE,1.936173,44.0,367,12.0,high,high
13002,23 Hesperia Avenue,City Beach,2437000,3,2,2.0,1052,278,1965.0,9400,...,6015,-31.930917,115.762400,NEWMAN COLLEGE,2.507512,44.0,774,56.0,high,high
10731,2 Viking Road,Dalkeith,2430000,5,3,3.0,1012,411,1997.0,7400,...,6009,-31.998400,115.802420,SANTA MARIA COLLEGE,2.332909,10.0,601,24.0,high,high
20083,38 Minora Road,Dalkeith,2425000,4,2,2.0,1115,377,1997.0,7700,...,6009,-31.999490,115.798990,SANTA MARIA COLLEGE,2.148030,10.0,738,24.0,high,high
30675,8 Briggs Street,Mosman Park,2425000,4,3,2.0,736,334,2011.0,11300,...,6012,-32.020138,115.770619,IONA PRESENTATION COLLEGE,1.319876,17.0,402,10.0,high,high
26398,59a West Coast Drive,Watermans Bay,2425000,4,4,2.0,912,272,2007.0,15200,...,6020,-31.849970,115.752130,CARINE SENIOR HIGH SCHOOL,2.266049,47.0,640,14.0,high,high
18064,31R Keane Street,Peppermint Grove,2425000,3,2,3.0,974,190,NaN,10300,...,6011,-32.000950,115.765764,ST HILDA'S ANGLICAN SCHOOL FOR GIRLS,0.495001,2.0,784,NaN,high,high
8603,17A View Street,Peppermint Grove,2425000,2,1,1.0,759,175,1960.0,10000,...,6011,-31.998340,115.767960,PRESBYTERIAN LADIES COLLEGE,0.601587,11.0,584,61.0,high,high
13346,239 Midland Road,Hazelmere,2420000,3,2,2.0,56878,230,1979.0,15500,...,6055,-31.928340,116.020270,YOUTH FUTURES COMMUNITY SCHOOL,4.212530,NaN,56648,42.0,high,high
16129,2A Conon Road,Applecross,2410000,4,2,8.0,675,310,2004.0,8100,...,6153,-32.020030,115.828545,APPLECROSS SENIOR HIGH SCHOOL,1.208991,34.0,365,17.0,high,high

In [31]:
# obtain the count of the number of houses in bentley
bentley_houses = len(df[df["SUBURB"] == "Bentley"])

# obtain the count of the number of houses in Peppermint Grove
peppermint_houses = len(df[df["SUBURB"] == "Peppermint Grove"])

# obtain the count of the number of rows that don't have data on ranking of nearest school
no_school_data = len(df[df["NEAREST_SCH_RANK"].isna()])

print(f"The number of houses in bentley are: {bentley_houses}")
print(f"The number of houses in peppermint grove are: {peppermint_houses}")
print(f"The number of houses that don't have data on nearest school ranking: {no_school_data}")

The number of houses in bentley are: 81
The number of houses in peppermint grove are: 41
The number of houses that don't have data on nearest school ranking: 10952

In [32]:
# get the unique list of suburb using .unique()
df["SUBURB"].unique()

array(['South Lake', 'Wandi', 'Camillo', 'Bellevue', 'Lockridge',
       'Mount Richon', 'Hilbert', 'Waikiki', 'Hamersley', 'Bayswater',
       'Carmel', 'Butler', 'Balga', 'Hammond Park', 'Wattle Grove',
       'Bull Creek', 'Bullsbrook', 'Maida Vale', 'Koongamia',
       'Mount Nasura', 'Forrestdale', 'Atwell', 'Ashby', 'Woodbridge',
       'Bicton', 'Singleton', 'South Guildford', 'Armadale', 'Kenwick',
       'Hamilton Hill', 'Port Kennedy', 'Roleystone', 'Glen Forrest',
       'Secret Harbour', 'Herne Hill', 'Gwelup', 'Harrisdale',
       'North Fremantle', 'Quinns Rocks', 'Spearwood', 'Parkwood',
       'Tapping', 'Thornlie', 'Baldivis', 'Kensington', 'Kiara', 'Menora',
       'Southern River', 'Bibra Lake', 'Swanbourne', 'The Vines',
       'Stratton', 'North Beach', 'Haynes', 'Madeley', 'Wembley Downs',
       'Bentley', 'Manning', 'Warwick', 'Queens Park', 'Medina',
       'Kalamunda', 'Merriwa', 'Aubin Grove', 'Karrinyup',
       'Gooseberry Hill', 'Darch', 'Hillarys', 'Alexander Heights',
       'St James', 'Bassendean', 'Ardross', 'Bedfordale', 'Success',
       'Ballajura', 'Leda', 'Bateman', 'Eglinton', 'Orelia', 'Beckenham',
       'Edgewater', 'Helena Valley', 'East Cannington', 'Marmion',
       'Maddington', 'Mount Claremont', 'Greenwood', 'Beechboro',
       'Wembley', 'Iluka', 'Mundaring', 'Salter Point', 'Mount Pleasant',
       'Warnbro', 'Byford', 'Willagee', 'Bertram', 'Mullaloo',
       'Woodlands', 'Wellard', 'Rossmoyne', 'Beaconsfield', 'Brentwood',
       'Carine', 'Beldon', 'Hillman', 'Swan View', 'Bennett Springs',
       'Claremont', 'Mount Hawthorn', 'Ferndale', 'Boya', 'Aveley',
       'Midland', 'High Wycombe', 'Kinross', 'Guildford', 'North Coogee',
       'Gnangara', 'Ascot', 'Osborne Park', 'Karragullen', 'Sinagra',
       'Darlington', 'Redcliffe', 'Pearsall', 'Huntingdale', 'Dayton',
       'Morley', 'Balcatta', 'Kwinana Town Centre', 'City Beach',
       'Two Rocks', 'Kallaroo', 'Banksia Grove', 'Noranda', 'Yangebup',
       'Mindarie', 'Calista', 'Marangaroo', 'Mount Helena', 'Duncraig',
       'Kewdale', 'Shoalwater', 'Melville', 'Leeming', 'Walliston',
       'Kardinya', 'Landsdale', 'Serpentine', 'Brookdale', 'Coolbellup',
       'Jandakot', 'Darling Downs', 'Hilton', 'Parkerville', 'Stoneville',
       'Coogee', 'Mirrabooka', 'Subiaco', 'Lesmurdie', 'Jane Brook',
       'Mahogany Creek', 'Middle Swan', 'Forrestfield', 'South Fremantle',
       'Rockingham', 'Dalkeith', 'Cannington', 'Seville Grove',
       'Safety Bay', 'Mosman Park', 'Ocean Reef', 'Jolimont', 'Carramar',
       'Viveash', 'Sawyers Valley', 'Connolly', 'Joondalup', 'Nedlands',
       'Ridgewood', 'Myaree', 'Applecross', 'Midvale', 'Ashfield',
       'Clarkson', 'Mardella', 'Burns Beach', 'Rivervale', 'Craigie',
       'Langford', 'Hocking', 'Parmelia', 'Piara Waters', 'Baskerville',
       'Cooloongup', 'Nollamara', 'Palmyra', 'Waterford', 'Currambine',
       'Beeliar', 'Sorrento', 'Churchlands', 'Woodvale', 'Trigg',
       'Stirling', 'Alkimos', 'Dianella', 'Bickley', 'Heathridge',
       'Cockburn Central', 'Mundijong', 'Willetton', 'Westminster',
       'Wilson', 'Brabham', 'Booragoon', 'Caversham', 'Samson',
       'Ellenbrook', 'Wanneroo', 'Orange Grove', 'Padbury',
       'White Gum Valley', 'Yokine', 'Cloverdale', 'Floreat',
       'Canning Vale', 'Burswood', 'North Lake', 'Koondoola', 'Kingsley',
       'Karawara', 'West Perth', 'Attadale', 'Crawley',
       'East Victoria Park', 'Joondanna', 'Lynwood', 'Tuart Hill',
       'South Perth', 'Greenmount', 'Highgate', 'Scarborough',
       'Watermans Bay', 'Inglewood', 'Cottesloe', 'Maylands',
       'East Fremantle', 'Leederville', 'Shelley', 'Daglish', 'Como',
       'Mount Lawley', 'Glendalough', 'Riverton', 'Murdoch', 'Eden Hill',
       'Girrawheen', 'Kelmscott', 'Doubleview', 'Champion Lakes',
       'West Leederville', 'Coolbinia', 'Yanchep', 'Henley Brook',
       'Peppermint Grove', 'Karnup', 'Hazelmere', 'Wooroloo',
       'Alfred Cove', 'Bedford', 'Jarrahdale', 'Jindalee', 'Lathlain',
       'Embleton', 'Martin', 'Oakford', 'Brigadoon', 'Winthrop',
       'Fremantle', 'North Perth', 'Cardup', 'Gosnells', 'Gidgegannup',
       'Shenton Park', 'Innaloo', "O'Connor", 'Pickering Brook', 'Whitby',
       'Golden Bay', 'West Swan', 'Hovea', 'Northbridge', 'Millendon',
       'Casuarina', 'Upper Swan', 'Mariginiup', 'Victoria Park',
       'Oldbury', 'Chidlow', 'Carabooda', 'Belhus', 'Belmont',
       'East Perth', 'Kwinana Beach', 'Keysbrook', 'Carlisle', 'Anketell',
       'Banjup', 'Jandabup', 'Wungong', 'Wattleup', 'Hopeland',
       'Neerabup', 'Treeby', 'Munster', 'Hope Valley', 'Welshpool',
       'Wangara', 'Naval Base'], dtype=object)

In [35]:
# get the unique list of SUBURBS that are within the boundary of Perth Modern School using .unique()
df[df["NEAREST_SCH"]=="PERTH MODERN SCHOOL"]["SUBURB"].unique()

array(['Wembley', 'Subiaco', 'West Leederville', 'Daglish', 'West Perth',
       'Shenton Park'], dtype=object)

In [50]:
# sort the houses that are less than 800k by nearest school ranking.
df[df["PRICE"] < 800000].sort_values(["NEAREST_SCH_RANK"], ascending=True).head(50)

,ADDRESS,SUBURB,PRICE,BEDROOMS,BATHROOMS,GARAGE,LAND_AREA,FLOOR_AREA,BUILD_YEAR,CBD_DIST,...,POSTCODE,LATITUDE,LONGITUDE,NEAREST_SCH,Dist_to_school,NEAREST_SCH_RANK,free_space,age,bucket,comment
27229,6 Robinson Terrace,Daglish,700000,3,2,1.0,2418,115,1983.0,4000,...,6008,-31.947626,115.817008,PERTH MODERN SCHOOL,1.851878,1.0,2303,38.0,low,low
28623,69/9 Delhi Street,West Perth,635000,3,2,2.0,154,101,2004.0,1400,...,6005,-31.946540,115.845870,PERTH MODERN SCHOOL,0.909118,1.0,53,17.0,low,low
24841,5/370 Barker Road,Subiaco,600000,3,1,1.0,3461,100,1977.0,3600,...,6008,-31.948430,115.821290,PERTH MODERN SCHOOL,1.474013,1.0,3361,44.0,low,low
5984,148 Tower Street,West Leederville,752500,3,1,NaN,294,116,NaN,2500,...,6007,-31.939190,115.837070,PERTH MODERN SCHOOL,0.656679,1.0,178,NaN,low,low
761,1/99 Roberts Road,Subiaco,450000,2,1,2.0,804,73,1986.0,2300,...,6008,-31.945750,115.835560,PERTH MODERN SCHOOL,0.109595,1.0,731,35.0,low,low
24797,5/1178 Hay Street,West Perth,407000,2,1,1.0,3365,56,2011.0,1500,...,6005,-31.948749,115.843829,PERTH MODERN SCHOOL,0.812448,1.0,3309,10.0,low,low
2865,11/3 Brigid Road,Subiaco,390000,1,1,1.0,3437,75,2000.0,3400,...,6008,-31.943980,115.824766,PERTH MODERN SCHOOL,1.104267,1.0,3362,21.0,low,low
26950,6 Kerr Street,West Leederville,715000,2,2,2.0,183,118,2007.0,2500,...,6007,-31.941836,115.835905,PERTH MODERN SCHOOL,0.362244,1.0,65,14.0,low,low
24793,5/11 Altona Street,West Perth,608000,2,2,1.0,129,93,2004.0,1800,...,6005,-31.951300,115.839360,PERTH MODERN SCHOOL,0.747716,1.0,36,17.0,low,low
6733,15/3 Brigid Road,Subiaco,443500,1,1,1.0,3437,75,2000.0,3400,...,6008,-31.943980,115.824766,PERTH MODERN SCHOOL,1.104267,1.0,3362,21.0,low,low
15656,28/237 Cambridge Street,Wembley,300000,2,1,1.0,2767,64,1985.0,3900,...,6014,-31.941107,115.820217,PERTH MODERN SCHOOL,1.589319,1.0,2703,36.0,low,low
127,1 Denton Street,Wembley,732000,3,1,2.0,328,145,1990.0,4200,...,6014,-31.941732,115.816700,PERTH MODERN SCHOOL,1.895645,1.0,183,31.0,low,low
28428,67/4 Delhi Street,West Perth,365000,2,2,1.0,3242,81,2006.0,1500,...,6005,-31.945285,115.845406,PERTH MODERN SCHOOL,0.850753,1.0,3161,15.0,low,low
4270,127 Carr Street,West Perth,678000,2,1,NaN,216,108,1900.0,1800,...,6005,-31.938688,115.848636,PERTH MODERN SCHOOL,1.355724,1.0,108,121.0,low,low
10064,1A Lesser Street,West Leederville,721500,3,2,2.0,202,109,1999.0,2700,...,6007,-31.940360,115.833470,PERTH MODERN SCHOOL,0.591830,1.0,93,22.0,low,low
4240,125B Tower Street,West Leederville,649000,3,2,2.0,230,97,1979.0,2400,...,6007,-31.939580,115.838231,PERTH MODERN SCHOOL,0.634312,1.0,133,42.0,low,low
7608,16/11 Altona Street,West Perth,380000,2,2,1.0,629,69,2004.0,1800,...,6005,-31.951300,115.839360,PERTH MODERN SCHOOL,0.747716,1.0,560,17.0,low,low
22405,43 Coldstream Street,West Leederville,750000,3,3,2.0,296,121,2003.0,2700,...,6007,-31.936290,115.836830,PERTH MODERN SCHOOL,0.977015,1.0,175,18.0,low,low
10627,2 Robinson Terrace,Daglish,730000,3,2,2.0,111,107,1983.0,4000,...,6008,-31.947626,115.817008,PERTH MODERN SCHOOL,1.851878,1.0,4,38.0,low,low
3234,119 Tower Street,West Leederville,685000,3,1,2.0,410,99,1982.0,2400,...,6007,-31.939578,115.838587,PERTH MODERN SCHOOL,0.644521,1.0,311,39.0,low,low
12754,226 Barker Road,Subiaco,750000,3,1,1.0,193,106,1993.0,3000,...,6008,-31.948520,115.827050,PERTH MODERN SCHOOL,0.962118,1.0,87,28.0,low,low
30276,76A Carr Street,West Perth,777500,3,2,2.0,668,143,NaN,1600,...,6005,-31.939299,115.851062,PERTH MODERN SCHOOL,1.525727,1.0,525,NaN,low,low
31482,8/1 Delhi Street,West Perth,540000,3,1,NaN,174,135,1997.0,1400,...,6005,-31.945850,115.846220,PERTH MODERN SCHOOL,0.931369,1.0,39,24.0,low,low
3890,12 Robinson Terrace,Daglish,740000,3,1,1.0,2418,112,1983.0,4000,...,6008,-31.947626,115.817008,PERTH MODERN SCHOOL,1.851878,1.0,2306,38.0,low,low
10875,2/32 Outram Street,West Perth,315000,1,1,1.0,675,67,2001.0,1900,...,6005,-31.949740,115.839449,PERTH MODERN SCHOOL,0.594451,1.0,608,20.0,low,low
589,1 White Place,Subiaco,753000,3,2,NaN,261,118,1988.0,2500,...,6008,-31.943061,115.834390,PERTH MODERN SCHOOL,0.292538,1.0,143,33.0,low,low
9148,18/4 Delhi Street,West Perth,440000,2,2,1.0,3242,77,2006.0,1500,...,6005,-31.945285,115.845406,PERTH MODERN SCHOOL,0.850753,1.0,3165,15.0,low,low
26259,58/4 Delhi Street,West Perth,345000,1,1,1.0,76,52,2006.0,1500,...,6005,-31.945285,115.845406,PERTH MODERN SCHOOL,0.850753,1.0,24,15.0,low,low
24863,5/8 Johnston Street,Peppermint Grove,599000,1,1,2.0,744,87,1994.0,10900,...,6011,-32.003670,115.760560,ST HILDA'S ANGLICAN SCHOOL FOR GIRLS,0.700974,2.0,657,27.0,low,low
668,1/23 Avonmore Terrace,Cottesloe,670000,2,1,1.0,910,62,1964.0,11500,...,6011,-32.003789,115.753697,ST HILDA'S ANGLICAN SCHOOL FOR GIRLS,1.338732,2.0,848,57.0,low,low
17224,3/14 Vaucluse Avenue,Claremont,450000,2,1,1.0,1959,62,1963.0,7600,...,6010,-31.980988,115.786130,CHRIST CHURCH GRAMMAR SCHOOL,0.995828,3.0,1897,58.0,low,low
8158,17 Mabel Street,Kensington,767000,3,1,NaN,690,119,1960.0,4300,...,6151,-31.987570,115.877530,PENRHOS COLLEGE,1.193579,4.0,571,61.0,low,low
15674,283 Canning Highway,Como,660000,4,1,3.0,454,150,1940.0,4400,...,6152,-31.990960,115.868643,PENRHOS COLLEGE,0.808185,4.0,304,81.0,low,low
33135,90 Todd Avenue,Como,675000,3,2,2.0,436,126,NaN,4900,...,6152,-31.993750,115.877160,PENRHOS COLLEGE,0.597996,4.0,310,NaN,low,low
9189,182 Labouchere Road,Como,735000,4,2,1.0,880,212,1957.0,4700,...,6152,-31.994180,115.860080,PENRHOS COLLEGE,1.229688,4.0,668,64.0,low,low
22814,44A Thelma Street,Como,791000,4,3,3.0,538,190,NaN,4900,...,6152,-31.996090,115.863563,PENRHOS COLLEGE,0.859835,4.0,348,NaN,low,low
25687,54A Hobbs Avenue,Como,762500,4,2,2.0,1012,129,NaN,4500,...,6152,-31.990584,115.875923,PENRHOS COLLEGE,0.825789,4.0,883,NaN,low,low
21818,40a Bessell Avenue,Como,771250,2,1,1.0,500,122,1955.0,4700,...,6152,-31.992640,115.872460,PENRHOS COLLEGE,0.532924,4.0,378,66.0,low,low
13356,23A David Street,Kensington,745000,3,2,2.0,569,164,1998.0,4300,...,6151,-31.987790,115.875900,PENRHOS COLLEGE,1.118217,4.0,405,23.0,low,low
13375,23B David Street,Kensington,745000,3,2,2.0,531,164,1998.0,4300,...,6151,-31.987790,115.875900,PENRHOS COLLEGE,1.118217,4.0,367,23.0,low,low
724,1/48 Thelma Street,Como,525000,3,2,2.0,1062,135,1993.0,5200,...,6152,-31.995950,115.864030,PENRHOS COLLEGE,0.819428,4.0,927,28.0,low,low
12411,22 Jenkins Place,Wembley Downs,730000,4,2,NaN,987,172,1986.0,9300,...,6019,-31.919854,115.768515,HALE SCHOOL,1.667214,6.0,815,35.0,low,low
9959,197B Hale Road,Wembley Downs,630000,2,1,2.0,802,70,1968.0,8200,...,6019,-31.915994,115.783882,HALE SCHOOL,0.408439,6.0,732,53.0,low,low
18744,33A Sulman Road,Wembley Downs,770000,4,2,2.0,1010,157,1999.0,9200,...,6019,-31.911900,115.774270,HALE SCHOOL,0.899413,6.0,853,22.0,low,low
26404,59B Hale Road,Wembley Downs,150000,3,1,2.0,434,144,1986.0,9700,...,6019,-31.913720,115.766700,HALE SCHOOL,1.620390,6.0,290,35.0,low,low
26112,57 Sulman Road,Wembley Downs,780000,3,1,2.0,364,123,1958.0,9400,...,6019,-31.912610,115.771120,HALE SCHOOL,1.196026,6.0,241,63.0,low,low
5131,13A Valley Road,Wembley Downs,605000,2,1,1.0,522,138,1979.0,9200,...,6019,-31.917547,115.771012,HALE SCHOOL,1.338530,6.0,384,42.0,low,low
4295,127A Cobb Street,Wembley Downs,729000,3,1,2.0,488,95,1980.0,9300,...,6019,-31.907678,115.775288,HALE SCHOOL,0.954020,6.0,393,41.0,low,low
31628,81A Glenelg Avenue,Wembley Downs,650000,2,1,1.0,72,63,1954.0,8700,...,6019,-31.918629,115.775750,HALE SCHOOL,1.033098,6.0,9,67.0,low,low
8577,179 Weaponess Road,Wembley Downs,735000,3,1,2.0,398,120,NaN,9200,...,6019,-31.914151,115.772387,HALE SCHOOL,1.095043,6.0,278,NaN,low,low