# Pandas exercises 

In this activity, we will perform some common operation in pandas.

In [1]:
import pandas as pd

In [3]:
# read a CSV into a DataFrame
df = pd.read_csv("https://raw.githubusercontent.com/AustralianSDAF/python-data-visualisation/main/perth_house_prices.csv")

In [4]:
df.head(5)

,ADDRESS,SUBURB,PRICE,BEDROOMS,BATHROOMS,GARAGE,LAND_AREA,FLOOR_AREA,BUILD_YEAR,CBD_DIST,NEAREST_STN,NEAREST_STN_DIST,DATE_SOLD,POSTCODE,LATITUDE,LONGITUDE,NEAREST_SCH,NEAREST_SCH_DIST,NEAREST_SCH_RANK
0,1 Acorn Place,South Lake,565000,4,2,2.0,600,160,2003.0,18300,Cockburn Central Station,1800,09-2018\r,6164,-32.115900,115.842450,LAKELAND SENIOR HIGH SCHOOL,0.828339,NaN
1,1 Addis Way,Wandi,365000,3,2,2.0,351,139,2013.0,26900,Kwinana Station,4900,02-2019\r,6167,-32.193470,115.859554,ATWELL COLLEGE,5.524324,129.0
2,1 Ainsley Court,Camillo,287000,3,1,1.0,719,86,1979.0,22600,Challis Station,1900,06-2015\r,6111,-32.120578,115.993579,KELMSCOTT SENIOR HIGH SCHOOL,1.649178,113.0
3,1 Albert Street,Bellevue,255000,2,1,2.0,651,59,1953.0,17900,Midland Station,3600,07-2018\r,6056,-31.900547,116.038009,SWAN VIEW SENIOR HIGH SCHOOL,1.571401,NaN
4,1 Aman Place,Lockridge,325000,4,1,2.0,466,131,1998.0,11200,Bassendean Station,2000,11-2016\r,6054,-31.885790,115.947780,KIARA COLLEGE,1.514922,NaN

## Activity 1

In [31]:
# obtain the count of the number of houses in bentley
bentley_houses = 

# obtain the count of the number of houses in Peppermint Grove
peppermint_houses = 

# obtain the count of the number of rows that don't have data on ranking of nearest school
no_school_data = 

print(f"The number of houses in bentley are: {bentley_houses}")
print(f"The number of houses in peppermint grove are: {peppermint_houses}")
print(f"The number of houses that don't have data on nearest school ranking: {no_school_data}")

The number of houses in bentley are: 81
The number of houses in peppermint grove are: 41
The number of houses that don't have data on nearest school ranking: 10952

## Activity 2

In [32]:
# get a unique list of all suburbs using .unique()

array(['South Lake', 'Wandi', 'Camillo', 'Bellevue', 'Lockridge',
       'Mount Richon', 'Hilbert', 'Waikiki', 'Hamersley', 'Bayswater',
       'Carmel', 'Butler', 'Balga', 'Hammond Park', 'Wattle Grove',
       'Bull Creek', 'Bullsbrook', 'Maida Vale', 'Koongamia',
       'Mount Nasura', 'Forrestdale', 'Atwell', 'Ashby', 'Woodbridge',
       'Bicton', 'Singleton', 'South Guildford', 'Armadale', 'Kenwick',
       'Hamilton Hill', 'Port Kennedy', 'Roleystone', 'Glen Forrest',
       'Secret Harbour', 'Herne Hill', 'Gwelup', 'Harrisdale',
       'North Fremantle', 'Quinns Rocks', 'Spearwood', 'Parkwood',
       'Tapping', 'Thornlie', 'Baldivis', 'Kensington', 'Kiara', 'Menora',
       'Southern River', 'Bibra Lake', 'Swanbourne', 'The Vines',
       'Stratton', 'North Beach', 'Haynes', 'Madeley', 'Wembley Downs',
       'Bentley', 'Manning', 'Warwick', 'Queens Park', 'Medina',
       'Kalamunda', 'Merriwa', 'Aubin Grove', 'Karrinyup',
       'Gooseberry Hill', 'Darch', 'Hillarys', 'Alexander Heights',
       'St James', 'Bassendean', 'Ardross', 'Bedfordale', 'Success',
       'Ballajura', 'Leda', 'Bateman', 'Eglinton', 'Orelia', 'Beckenham',
       'Edgewater', 'Helena Valley', 'East Cannington', 'Marmion',
       'Maddington', 'Mount Claremont', 'Greenwood', 'Beechboro',
       'Wembley', 'Iluka', 'Mundaring', 'Salter Point', 'Mount Pleasant',
       'Warnbro', 'Byford', 'Willagee', 'Bertram', 'Mullaloo',
       'Woodlands', 'Wellard', 'Rossmoyne', 'Beaconsfield', 'Brentwood',
       'Carine', 'Beldon', 'Hillman', 'Swan View', 'Bennett Springs',
       'Claremont', 'Mount Hawthorn', 'Ferndale', 'Boya', 'Aveley',
       'Midland', 'High Wycombe', 'Kinross', 'Guildford', 'North Coogee',
       'Gnangara', 'Ascot', 'Osborne Park', 'Karragullen', 'Sinagra',
       'Darlington', 'Redcliffe', 'Pearsall', 'Huntingdale', 'Dayton',
       'Morley', 'Balcatta', 'Kwinana Town Centre', 'City Beach',
       'Two Rocks', 'Kallaroo', 'Banksia Grove', 'Noranda', 'Yangebup',
       'Mindarie', 'Calista', 'Marangaroo', 'Mount Helena', 'Duncraig',
       'Kewdale', 'Shoalwater', 'Melville', 'Leeming', 'Walliston',
       'Kardinya', 'Landsdale', 'Serpentine', 'Brookdale', 'Coolbellup',
       'Jandakot', 'Darling Downs', 'Hilton', 'Parkerville', 'Stoneville',
       'Coogee', 'Mirrabooka', 'Subiaco', 'Lesmurdie', 'Jane Brook',
       'Mahogany Creek', 'Middle Swan', 'Forrestfield', 'South Fremantle',
       'Rockingham', 'Dalkeith', 'Cannington', 'Seville Grove',
       'Safety Bay', 'Mosman Park', 'Ocean Reef', 'Jolimont', 'Carramar',
       'Viveash', 'Sawyers Valley', 'Connolly', 'Joondalup', 'Nedlands',
       'Ridgewood', 'Myaree', 'Applecross', 'Midvale', 'Ashfield',
       'Clarkson', 'Mardella', 'Burns Beach', 'Rivervale', 'Craigie',
       'Langford', 'Hocking', 'Parmelia', 'Piara Waters', 'Baskerville',
       'Cooloongup', 'Nollamara', 'Palmyra', 'Waterford', 'Currambine',
       'Beeliar', 'Sorrento', 'Churchlands', 'Woodvale', 'Trigg',
       'Stirling', 'Alkimos', 'Dianella', 'Bickley', 'Heathridge',
       'Cockburn Central', 'Mundijong', 'Willetton', 'Westminster',
       'Wilson', 'Brabham', 'Booragoon', 'Caversham', 'Samson',
       'Ellenbrook', 'Wanneroo', 'Orange Grove', 'Padbury',
       'White Gum Valley', 'Yokine', 'Cloverdale', 'Floreat',
       'Canning Vale', 'Burswood', 'North Lake', 'Koondoola', 'Kingsley',
       'Karawara', 'West Perth', 'Attadale', 'Crawley',
       'East Victoria Park', 'Joondanna', 'Lynwood', 'Tuart Hill',
       'South Perth', 'Greenmount', 'Highgate', 'Scarborough',
       'Watermans Bay', 'Inglewood', 'Cottesloe', 'Maylands',
       'East Fremantle', 'Leederville', 'Shelley', 'Daglish', 'Como',
       'Mount Lawley', 'Glendalough', 'Riverton', 'Murdoch', 'Eden Hill',
       'Girrawheen', 'Kelmscott', 'Doubleview', 'Champion Lakes',
       'West Leederville', 'Coolbinia', 'Yanchep', 'Henley Brook',
       'Peppermint Grove', 'Karnup', 'Hazelmere', 'Wooroloo',
       'Alfred Cove', 'Bedford', 'Jarrahdale', 'Jindalee', 'Lathlain',
       'Embleton', 'Martin', 'Oakford', 'Brigadoon', 'Winthrop',
       'Fremantle', 'North Perth', 'Cardup', 'Gosnells', 'Gidgegannup',
       'Shenton Park', 'Innaloo', "O'Connor", 'Pickering Brook', 'Whitby',
       'Golden Bay', 'West Swan', 'Hovea', 'Northbridge', 'Millendon',
       'Casuarina', 'Upper Swan', 'Mariginiup', 'Victoria Park',
       'Oldbury', 'Chidlow', 'Carabooda', 'Belhus', 'Belmont',
       'East Perth', 'Kwinana Beach', 'Keysbrook', 'Carlisle', 'Anketell',
       'Banjup', 'Jandabup', 'Wungong', 'Wattleup', 'Hopeland',
       'Neerabup', 'Treeby', 'Munster', 'Hope Valley', 'Welshpool',
       'Wangara', 'Naval Base'], dtype=object)

## Activity 3

In [35]:
# get the unique list of SUBURBS that are within the boundary of Perth Modern School using .unique()

array(['Wembley', 'Subiaco', 'West Leederville', 'Daglish', 'West Perth',
       'Shenton Park'], dtype=object)

## Activity 5

In [5]:
# find the houses that are less than $800k and sort by nearest school ranking in ascending order.

,ADDRESS,SUBURB,PRICE,BEDROOMS,BATHROOMS,GARAGE,LAND_AREA,FLOOR_AREA,BUILD_YEAR,CBD_DIST,NEAREST_STN,NEAREST_STN_DIST,DATE_SOLD,POSTCODE,LATITUDE,LONGITUDE,NEAREST_SCH,NEAREST_SCH_DIST,NEAREST_SCH_RANK
27229,6 Robinson Terrace,Daglish,700000,3,2,1.0,2418,115,1983.0,4000,Daglish Station,615,11-2011\r,6008,-31.947626,115.817008,PERTH MODERN SCHOOL,1.851878,1.0
28623,69/9 Delhi Street,West Perth,635000,3,2,2.0,154,101,2004.0,1400,City West Station,154,08-2018\r,6005,-31.946540,115.845870,PERTH MODERN SCHOOL,0.909118,1.0
24841,5/370 Barker Road,Subiaco,600000,3,1,1.0,3461,100,1977.0,3600,Subiaco Station,500,09-2019\r,6008,-31.948430,115.821290,PERTH MODERN SCHOOL,1.474013,1.0
5984,148 Tower Street,West Leederville,752500,3,1,NaN,294,116,NaN,2500,Leederville Station,299,09-2017\r,6007,-31.939190,115.837070,PERTH MODERN SCHOOL,0.656679,1.0
761,1/99 Roberts Road,Subiaco,450000,2,1,2.0,804,73,1986.0,2300,West Leederville Station,406,12-2019\r,6008,-31.945750,115.835560,PERTH MODERN SCHOOL,0.109595,1.0
24797,5/1178 Hay Street,West Perth,407000,2,1,1.0,3365,56,2011.0,1500,City West Station,460,04-2018\r,6005,-31.948749,115.843829,PERTH MODERN SCHOOL,0.812448,1.0
2865,11/3 Brigid Road,Subiaco,390000,1,1,1.0,3437,75,2000.0,3400,Subiaco Station,95,08-2018\r,6008,-31.943980,115.824766,PERTH MODERN SCHOOL,1.104267,1.0
26950,6 Kerr Street,West Leederville,715000,2,2,2.0,183,118,2007.0,2500,West Leederville Station,274,01-2017\r,6007,-31.941836,115.835905,PERTH MODERN SCHOOL,0.362244,1.0
24793,5/11 Altona Street,West Perth,608000,2,2,1.0,129,93,2004.0,1800,City West Station,924,03-2018\r,6005,-31.951300,115.839360,PERTH MODERN SCHOOL,0.747716,1.0
6733,15/3 Brigid Road,Subiaco,443500,1,1,1.0,3437,75,2000.0,3400,Subiaco Station,95,06-2018\r,6008,-31.943980,115.824766,PERTH MODERN SCHOOL,1.104267,1.0
15656,28/237 Cambridge Street,Wembley,300000,2,1,1.0,2767,64,1985.0,3900,Subiaco Station,552,08-2020\r,6014,-31.941107,115.820217,PERTH MODERN SCHOOL,1.589319,1.0
127,1 Denton Street,Wembley,732000,3,1,2.0,328,145,1990.0,4200,Subiaco Station,786,03-2019\r,6014,-31.941732,115.816700,PERTH MODERN SCHOOL,1.895645,1.0
28428,67/4 Delhi Street,West Perth,365000,2,2,1.0,3242,81,2006.0,1500,City West Station,46,10-2020\r,6005,-31.945285,115.845406,PERTH MODERN SCHOOL,0.850753,1.0
4270,127 Carr Street,West Perth,678000,2,1,NaN,216,108,1900.0,1800,Leederville Station,796,10-2019\r,6005,-31.938688,115.848636,PERTH MODERN SCHOOL,1.355724,1.0
10064,1A Lesser Street,West Leederville,721500,3,2,2.0,202,109,1999.0,2700,West Leederville Station,262,12-2016\r,6007,-31.940360,115.833470,PERTH MODERN SCHOOL,0.591830,1.0
4240,125B Tower Street,West Leederville,649000,3,2,2.0,230,97,1979.0,2400,Leederville Station,200,03-2020\r,6007,-31.939580,115.838231,PERTH MODERN SCHOOL,0.634312,1.0
7608,16/11 Altona Street,West Perth,380000,2,2,1.0,629,69,2004.0,1800,City West Station,924,06-2020\r,6005,-31.951300,115.839360,PERTH MODERN SCHOOL,0.747716,1.0
22405,43 Coldstream Street,West Leederville,750000,3,3,2.0,296,121,2003.0,2700,Leederville Station,438,05-2018\r,6007,-31.936290,115.836830,PERTH MODERN SCHOOL,0.977015,1.0
10627,2 Robinson Terrace,Daglish,730000,3,2,2.0,111,107,1983.0,4000,Daglish Station,615,12-2017\r,6008,-31.947626,115.817008,PERTH MODERN SCHOOL,1.851878,1.0
3234,119 Tower Street,West Leederville,685000,3,1,2.0,410,99,1982.0,2400,Leederville Station,169,02-2017\r,6007,-31.939578,115.838587,PERTH MODERN SCHOOL,0.644521,1.0
12754,226 Barker Road,Subiaco,750000,3,1,1.0,193,106,1993.0,3000,Subiaco Station,501,10-2019\r,6008,-31.948520,115.827050,PERTH MODERN SCHOOL,0.962118,1.0
30276,76A Carr Street,West Perth,777500,3,2,2.0,668,143,NaN,1600,City West Station,810,08-2018\r,6005,-31.939299,115.851062,PERTH MODERN SCHOOL,1.525727,1.0
31482,8/1 Delhi Street,West Perth,540000,3,1,NaN,174,135,1997.0,1400,City West Station,122,03-2020\r,6005,-31.945850,115.846220,PERTH MODERN SCHOOL,0.931369,1.0
3890,12 Robinson Terrace,Daglish,740000,3,1,1.0,2418,112,1983.0,4000,Daglish Station,615,01-2013\r,6008,-31.947626,115.817008,PERTH MODERN SCHOOL,1.851878,1.0
10875,2/32 Outram Street,West Perth,315000,1,1,1.0,675,67,2001.0,1900,City West Station,791,09-2019\r,6005,-31.949740,115.839449,PERTH MODERN SCHOOL,0.594451,1.0
589,1 White Place,Subiaco,753000,3,2,NaN,261,118,1988.0,2500,West Leederville Station,119,10-2020\r,6008,-31.943061,115.834390,PERTH MODERN SCHOOL,0.292538,1.0
9148,18/4 Delhi Street,West Perth,440000,2,2,1.0,3242,77,2006.0,1500,City West Station,46,02-2018\r,6005,-31.945285,115.845406,PERTH MODERN SCHOOL,0.850753,1.0
26259,58/4 Delhi Street,West Perth,345000,1,1,1.0,76,52,2006.0,1500,City West Station,46,02-2018\r,6005,-31.945285,115.845406,PERTH MODERN SCHOOL,0.850753,1.0
24863,5/8 Johnston Street,Peppermint Grove,599000,1,1,2.0,744,87,1994.0,10900,Mosman Park Station,489,02-2010\r,6011,-32.003670,115.760560,ST HILDA'S ANGLICAN SCHOOL FOR GIRLS,0.700974,2.0
668,1/23 Avonmore Terrace,Cottesloe,670000,2,1,1.0,910,62,1964.0,11500,Mosman Park Station,507,11-2020\r,6011,-32.003789,115.753697,ST HILDA'S ANGLICAN SCHOOL FOR GIRLS,1.338732,2.0
17224,3/14 Vaucluse Avenue,Claremont,450000,2,1,1.0,1959,62,1963.0,7600,Claremont Station,399,06-2018\r,6010,-31.980988,115.786130,CHRIST CHURCH GRAMMAR SCHOOL,0.995828,3.0
8158,17 Mabel Street,Kensington,767000,3,1,NaN,690,119,1960.0,4300,Oats Street Station,3600,12-2014\r,6151,-31.987570,115.877530,PENRHOS COLLEGE,1.193579,4.0
15674,283 Canning Highway,Como,660000,4,1,3.0,454,150,1940.0,4400,Canning Bridge Station,2400,12-2019\r,6152,-31.990960,115.868643,PENRHOS COLLEGE,0.808185,4.0
33135,90 Todd Avenue,Como,675000,3,2,2.0,436,126,NaN,4900,Canning Bridge Station,2700,08-2019\r,6152,-31.993750,115.877160,PENRHOS COLLEGE,0.597996,4.0
9189,182 Labouchere Road,Como,735000,4,2,1.0,880,212,1957.0,4700,Canning Bridge Station,1800,07-2019\r,6152,-31.994180,115.860080,PENRHOS COLLEGE,1.229688,4.0
22814,44A Thelma Street,Como,791000,4,3,3.0,538,190,NaN,4900,Canning Bridge Station,1700,11-2019\r,6152,-31.996090,115.863563,PENRHOS COLLEGE,0.859835,4.0
25687,54A Hobbs Avenue,Como,762500,4,2,2.0,1012,129,NaN,4500,Canning Bridge Station,2900,05-2019\r,6152,-31.990584,115.875923,PENRHOS COLLEGE,0.825789,4.0
21818,40a Bessell Avenue,Como,771250,2,1,1.0,500,122,1955.0,4700,Canning Bridge Station,2500,09-2020\r,6152,-31.992640,115.872460,PENRHOS COLLEGE,0.532924,4.0
13356,23A David Street,Kensington,745000,3,2,2.0,569,164,1998.0,4300,Oats Street Station,3800,04-2016\r,6151,-31.987790,115.875900,PENRHOS COLLEGE,1.118217,4.0
13375,23B David Street,Kensington,745000,3,2,2.0,531,164,1998.0,4300,Oats Street Station,3800,05-2016\r,6151,-31.987790,115.875900,PENRHOS COLLEGE,1.118217,4.0
724,1/48 Thelma Street,Como,525000,3,2,2.0,1062,135,1993.0,5200,Canning Bridge Station,2500,06-2019\r,6152,-31.995950,115.864030,PENRHOS COLLEGE,0.819428,4.0
12411,22 Jenkins Place,Wembley Downs,730000,4,2,NaN,987,172,1986.0,9300,Glendalough Station,5200,10-2019\r,6019,-31.919854,115.768515,HALE SCHOOL,1.667214,6.0
9959,197B Hale Road,Wembley Downs,630000,2,1,2.0,802,70,1968.0,8200,Glendalough Station,3700,10-2018\r,6019,-31.915994,115.783882,HALE SCHOOL,0.408439,6.0
18744,33A Sulman Road,Wembley Downs,770000,4,2,2.0,1010,157,1999.0,9200,Stirling Station,3500,12-2016\r,6019,-31.911900,115.774270,HALE SCHOOL,0.899413,6.0
26404,59B Hale Road,Wembley Downs,150000,3,1,2.0,434,144,1986.0,9700,Glendalough Station,5300,05-2017\r,6019,-31.913720,115.766700,HALE SCHOOL,1.620390,6.0
26112,57 Sulman Road,Wembley Downs,780000,3,1,2.0,364,123,1958.0,9400,Stirling Station,3800,03-2018\r,6019,-31.912610,115.771120,HALE SCHOOL,1.196026,6.0
5131,13A Valley Road,Wembley Downs,605000,2,1,1.0,522,138,1979.0,9200,Glendalough Station,5000,11-2016\r,6019,-31.917547,115.771012,HALE SCHOOL,1.338530,6.0
4295,127A Cobb Street,Wembley Downs,729000,3,1,2.0,488,95,1980.0,9300,Stirling Station,3100,06-2018\r,6019,-31.907678,115.775288,HALE SCHOOL,0.954020,6.0
31628,81A Glenelg Avenue,Wembley Downs,650000,2,1,1.0,72,63,1954.0,8700,Glendalough Station,4500,09-2017\r,6019,-31.918629,115.775750,HALE SCHOOL,1.033098,6.0
8577,179 Weaponess Road,Wembley Downs,735000,3,1,2.0,398,120,NaN,9200,Glendalough Station,4800,10-2020\r,6019,-31.914151,115.772387,HALE SCHOOL,1.095043,6.0